
insert into Bank (code, name, type) Values

('001', 'Banco do Brasil', 'CB'),
('003', 'Banco da Amazônia', 'CB'),
('004', 'Banco do Nordeste', 'CB'),
('021', 'Banestes', 'CB'),
('025', 'Alfa', 'CB'),
('029', 'Banerj', 'CB'),
('033', 'Santander', 'CB'),
('037', 'Banpará', 'CB'),
('041', 'Banrisul', 'CB'),
('047', 'Banese', 'CB'),
('070', 'BRB - Banco de Brasília', 'CB'),
('077', 'Banco Intermedium', 'CB'),
('083', 'China Brasil', 'CB'),
('084', 'Uniprime Norte do Paraná', 'CB'),
('085', 'Cecred (Viacredi / CredCrea)', 'CB'),
('090', 'Unicred', 'CB'),
('091', 'Unicred Central do Rio Grande do Sul', 'CB'),
('094', 'Petra', 'CB'),
('095', 'Confidence', 'CB'),
('096', 'Banco BMeF Bovespa', 'CB'),
('097', 'CrediSIS', 'CB'),
('099', 'Uniprime', 'CB'),
('102', 'XP Investimentos', 'CB'),
('104', 'Caixa Econômica Federal', 'CB'),
('121', 'Agiplan', 'CB'),
('124', 'Woori Bank', 'CB'),
('132', 'ICBC do Brasil', 'CB'),
('136', 'Centrais Unicreds', 'CB'),
('147', 'Rico', 'CB'),
('151', 'Nossa Caixa', 'CB'),
('208', 'BTG Pactual', 'CB'),
('212', 'Original', 'CB'),
('213', 'ARBI', 'CB'),
('218', 'Banco Bonsucesso', 'CB'),
('224', 'Fibra', 'CB'),
('237', 'Bradesco', 'CB'),
('243', 'Banco Máxima', 'CB'),
('246', 'Banco ABC Brasil', 'CB'),
('250', 'BCV - Banco de Crédito e Varejo', 'CB'),
('254', 'ParanáBanco', 'CB'),
('318', 'Banco BMG', 'CB'),
('320', 'BIC Banco Industrial e Comercial', 'CB'),
('341', 'Itaú Unibanco', 'CB'),
('376', 'J. P. Morgan', 'CB'),
('389', 'Banco Mercantil do Brasil', 'CB'),
('399', 'HSBC Bank', 'CB'),
('422', 'Safra', 'CB'),
('453', 'Banco Rural S.A.', 'CB'),
('456', 'Banco de Tokyo', 'CB'),
('464', 'Banco Sumitomo Mitsui Brasileiro', 'CB'),
('473', 'Caixa Geral', 'CB'),
('487', 'Deutsche Bank', 'CB'),
('600', 'Banco Luso Brasileiro', 'CB'),
('604', 'Banco Industrial do Brasil', 'CB'),
('611', 'Banco Paulista', 'CB'),
('612', 'Banco Guanabara', 'CB'),
('633', 'Rendimento', 'CB'),
('637', 'Sofisa', 'CB'),
('643', 'Pine', 'CB'),
('653', 'Indusval', 'CB'),
('654', 'Banco Renner', 'CB'),
('655', 'Votorantin', 'CB'),
('707', 'Banco Daycoval', 'CB'),
('712', 'Ourinvest', 'CB'),
('719', 'Banif', 'CB'),
('735', 'Neon / Pottencial', 'CB'),
('743', 'Banco Semear', 'CB'),
('745', 'Citibank S.A.', 'CB'),
('748', 'Sicredi', 'CB'),
('752', 'BNP Paribas', 'CB'),
('755', 'Bank of America Merrill Lynch', 'CB'),
('756', 'Sicoob', 'CB'),
('888', 'MundiPagg', 'CV'),
('889', 'ABC Asset', 'CB'),
('890', 'Banese Card', 'AC'),
('891', 'Porto Seguro', 'AC'),
('892', 'iFood', 'AC'),
('893', 'Beblue', 'AC'),
('894', 'AZ Brasil', 'CB'),
('895', 'Pagar.me', 'CV'),
('896', 'Dot Bank', 'CB'),
('897', 'Mercado Pago', 'CV'),
('898', 'Cresol', 'CB'),
('899', 'Fortumno', 'CV'),
('900', 'PayZen', 'CV'),
('901', 'Vindi', 'CV'),
('902', 'TrayCheckout', 'CV'),
('903', 'ICAP Brasil', 'CB'),
('904', 'UBS Ag', 'CB'),
('905', 'Axis Soluções Financeiras', 'CB'),
('906', 'Dacasa Financeira', 'AC'),
('907', 'Capital Ativo', 'CB'),
('909', 'Sumup', 'AC'),
('910', 'Credifisco', 'CB'),
('911', 'JCF Factoring', 'CB'),
('912', 'Araguaya', 'CB'),
('913', 'Pague Veloz', 'CV'),
('914', 'CRR Factoring', 'CB'),
('915', 'London Factoring', 'CB'),
('916', 'Globalcash', 'CB'),
('917', 'Target Fomento', 'CB'),
('918', 'Santa Cristina Fomento', 'CB'),
('919', 'RM Fomento', 'CB'),
('920', 'Stripe', 'CV'),
('921', 'Omni Soluções Financeiras', 'CB'),
('922', 'Santana Financeira', 'CB'),
('923', 'Acesso Card', 'AC'),
('924', 'PayU', 'CV'),
('925', 'Global Payments', 'AC'),
('926', 'Payleven', 'AC'),
('927', 'Continental Banco Fomento', 'CB'),
('928', 'SR Bank', 'CB'),
('929', 'Algarve Fomento', 'CB'),
('930', 'RA Fomento', 'CB'),
('931', 'Simetrica Eficiência Financeira', 'CB'),
('932', 'Capital Bank', 'CB'),
('933', 'WidePay', 'CV'),
('934', 'Verde Card', 'AC'),
('935', 'Banricompras', 'AC'),
('936', 'Brasil Pré-Pagos', 'AC'),
('937', 'GerenciaNet', 'CV'),
('938', 'Conta Super', 'CB'),
('939', 'Hotmart', 'CV'),
('940', 'Lecca Financeira', 'CB'),
('941', 'BRR FIDC', 'CB'),
('942', 'Belluno FIDC', 'CB'),
('943', 'Elavon', 'AC'),
('944', 'Grupo Sifra', 'CB'),
('945', 'Work Capital', 'CB'),
('946', 'Iugu', 'CV'),
('947', 'Bcash', 'CV'),
('948', 'Cabal', 'AC'),
('949', 'Payoneer', 'CV'),
('950', 'PagSeguro', 'AC'),
('951', 'Up Plan', 'AC'),
('952', 'Nubank', 'AC'),
('953', 'VR', 'AC'),
('954', 'Cred-System', 'AC'),
('955', 'Alelo', 'AC'),
('956', 'BIN', 'AC'),
('957', 'Stone', 'AC'),
('958', 'Sipag', 'AC'),
('959', 'Google', 'CV'),
('960', 'Green Card', 'AC'),
('961', 'Ticket', 'AC'),
('962', 'Peixe Urbano', 'CV'),
('963', 'iZettle', 'AC'),
('964', 'Groupon', 'CV'),
('965', 'Extra.com.br', 'CV'),
('966', 'Rakuten', 'CV'),
('967', 'Kanui', 'CV'),
('968', 'Moip', 'CV'),
('969', 'Mercado Livre', 'CV'),
('970', 'Visa', 'AC'),
('971', 'Redecard', 'AC'),
('972', 'Hipercard', 'AC'),
('973', 'American', 'AC'),
('974', 'Sorocred', 'AC'),
('975', 'TecBan', 'AC'),
('976', 'CIELO', 'AC'),
('977', 'GetNet', 'AC'),
('978', 'Sodexo', 'AC'),
('979', 'Verocard', 'AC'),
('980', 'JCB', 'CR'),
('981', 'Maestro', 'CR'),
('982', 'Sorocred', 'CR'),
('983', 'Aura', 'CR'),
('984', 'Discover', 'CR'),
('985', 'Visa', 'CR'),
('986', 'MasterCard', 'CR'),
('987', 'American Express', 'CR'),
('988', 'Diners Club', 'CR'),
('989', 'Hipercard', 'CR'),
('990', 'PayPal', 'CV'),
('991', 'PagSeguro', 'CV'),
('992', 'Elo', 'CR'),
('993', 'BNDES', 'CR'),
('994', 'CredSystem', 'CR'),
('995', 'ASAAS', 'CV'),
('996', 'B2W', 'CV'),
('997', 'Walmart', 'CV'),
('998', 'Nova PontoCom', 'CV'),
('999', '-sem instituição-', 'CX');
